$env:POLYMARKET_PRIVATE_KEY = "0xYOUR_PRIVATE_KEY"
$env:POLYMARKET_FUNDER_ADDRESS = "0xYOUR_FUNDER_ADDRESS"
$env:POLYMARKET_WALLET_ADDRESS = "0xYOUR_WALLET_ADDRESS"
$env:POLYMARKET_SIGNATURE_TYPE = "3"
$env:POLYGON_RPC_URL = "https://1rpc.io/matic"

# Optional overrides:
# $env:POLYMARKET_MAX_DAILY_LOSS_U = "126"
# $env:POLYMARKET_MAX_CONSECUTIVE_BLOWUPS = "1"
# $env:POLYMARKET_MAX_API_FAILURES = "3"
